/**
 * Firestore Vector Embeddings - TypeScript Types
 *
 * This module defines the TypeScript interfaces for working with
 * vector embeddings in Firestore. These types match the data model
 * used by the Cloud Functions.
 *
 * @example
 * ```typescript
 * import { DocumentContent, ContentEmbedding, SearchResult } from './types';
 *
 * const doc: DocumentContent = {
 *   title: "7nm FinFET Process Flow",
 *   summary: "Complete gate-first HKMG integration",
 *   details: "This document describes...",
 *   category: "process_flow",
 *   contentUpdatedAt: new Date().toISOString(),
 * };
 * ```
 */

// =============================================================================
// Document Content Types
// =============================================================================

/**
 * Content field structure for documents that support embedding.
 *
 * This interface defines the text content that will be embedded
 * for semantic search.
 */
export interface DocumentContent {
  /** Document title for display purposes */
  title: string;

  /** Short summary of the document (1-2 sentences) */
  summary: string;

  /** Full document text/details for embedding */
  details: string;

  /** Category for filtering (e.g., "process_flow", "design_spec") */
  category?: string;

  /** ISO timestamp when content was last updated */
  contentUpdatedAt: string;
}

/**
 * Vector embedding stored on the document.
 *
 * This field is automatically generated by the Firestore trigger
 * and should never be written directly by clients.
 */
export interface ContentEmbedding {
  /**
   * 2048-dimensional embedding vector.
   * Stored as Firestore Vector type, appears as number[] in JS.
   */
  vector: number[];

  /** ISO timestamp when embedding was generated */
  embeddedAt: string;

  /** Model used to generate the embedding (e.g., "gemini-embedding-001") */
  modelVersion: string;
}

/**
 * Complete document structure with optional embedding.
 *
 * @example
 * ```typescript
 * const doc: EmbeddableDocument = {
 *   id: "doc123",
 *   content: {
 *     title: "SRAM Cell Design",
 *     summary: "6T SRAM cell for 28nm node",
 *     details: "...",
 *     contentUpdatedAt: "2026-01-15T10:30:00Z"
 *   },
 *   // contentEmbedding is auto-generated by trigger
 * };
 * ```
 */
export interface EmbeddableDocument {
  /** Firestore document ID */
  id: string;

  /** Document content for embedding */
  content: DocumentContent;

  /** Auto-generated embedding (read-only from client perspective) */
  contentEmbedding?: ContentEmbedding;

  /** Additional metadata fields */
  createdAt?: string;
  updatedAt?: string;
  createdBy?: string;
}

// =============================================================================
// Search Types
// =============================================================================

/**
 * Request parameters for vector search.
 */
export interface SearchRequest {
  /** Path to the collection to search (e.g., "documents") */
  collectionPath?: string;

  /** Natural language search query (minimum 3 characters) */
  query: string;

  /**
   * Maximum number of results to return.
   * Default: 20, Maximum: 50
   */
  limit?: number;

  /**
   * Similarity threshold for filtering results.
   * Range: 0.0 to 1.0
   * - 0.0 = Include all results
   * - 0.5 = Default, moderate matching (recommended)
   * - 1.0 = Only exact matches
   *
   * Higher values = stricter matching, fewer results.
   */
  threshold?: number;
}

/**
 * Individual search result returned by vector search.
 */
export interface SearchResult {
  /** Firestore document ID */
  documentId: string;

  /**
   * DOT_PRODUCT similarity score from query embedding.
   * Range: -1.0 to 1.0 (higher = more similar)
   */
  similarity: number;

  /**
   * Human-readable relevance score.
   * Range: 0 to 100
   * - 100 = Perfect match
   * - 50 = Good match
   * - 0 = Poor match
   */
  relevanceScore: number;

  /** Document summary for preview */
  summary: string;

  /** Document category */
  category?: string;

  /** Document title */
  title?: string;
}

/**
 * Response from vector search function.
 */
export interface SearchResponse {
  /** Whether the search completed successfully */
  success: boolean;

  /** Array of matching documents, sorted by relevance */
  results: SearchResult[];

  /** The original search query */
  query: string;

  /** Total number of documents searched (with embeddings) */
  totalSearched: number;
}

// =============================================================================
// Backfill Types
// =============================================================================

/**
 * Request parameters for embedding backfill.
 */
export interface BackfillRequest {
  /** Path to the collection to process */
  collectionPath?: string;

  /**
   * Maximum documents to process in this call.
   * Default: 50, Maximum: 200
   */
  limit?: number;
}

/**
 * Response from backfill function.
 */
export interface BackfillResponse {
  /** Whether the backfill completed successfully */
  success: boolean;

  /** Number of embeddings generated in this call */
  processed: number;

  /** Estimated remaining documents needing embeddings */
  remaining: number;

  /** The collection that was processed */
  collectionPath: string;

  /** Document IDs that failed to process */
  errors: string[];
}

/**
 * Statistics about embedding coverage.
 */
export interface EmbeddingStats {
  /** Total documents in the collection */
  totalDocuments: number;

  /** Documents with up-to-date embeddings */
  withEmbedding: number;

  /** Documents missing embeddings */
  withoutEmbedding: number;

  /** Documents with outdated embeddings */
  outdatedEmbedding: number;

  /** Percentage of documents with current embeddings (0-100) */
  coveragePercent: number;
}

// =============================================================================
// Error Types
// =============================================================================

/**
 * Typed error from Cloud Functions.
 *
 * Firebase Functions errors include a code that helps identify
 * the type of error for appropriate handling.
 */
export interface FunctionsError extends Error {
  /** Firebase Functions error code */
  code:
    | 'unauthenticated'
    | 'permission-denied'
    | 'invalid-argument'
    | 'not-found'
    | 'failed-precondition'
    | 'internal';

  /** Error details if available */
  details?: unknown;
}

/**
 * Type guard to check if an error is a FunctionsError.
 */
export function isFunctionsError(error: unknown): error is FunctionsError {
  return (
    error instanceof Error &&
    'code' in error &&
    typeof (error as FunctionsError).code === 'string'
  );
}
