"""
Firestore Vector Embeddings - Python Types

This module defines Python type definitions for working with
vector embeddings in Firestore. Uses dataclasses for structured data
and TypedDict for dictionary-based responses.

Example:
    >>> from types import DocumentContent, SearchResult
    >>>
    >>> content = DocumentContent(
    ...     title="7nm FinFET Process Flow",
    ...     summary="Complete gate-first HKMG integration",
    ...     details="This document describes...",
    ...     category="process_flow",
    ...     content_updated_at="2026-01-15T10:30:00Z"
    ... )
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TypedDict, List, Optional, Any


# =============================================================================
# Document Content Types
# =============================================================================

@dataclass
class DocumentContent:
    """
    Content field structure for documents that support embedding.

    This class defines the text content that will be embedded
    for semantic search.

    Attributes:
        title: Document title for display purposes.
        summary: Short summary of the document (1-2 sentences).
        details: Full document text/details for embedding.
        category: Category for filtering (e.g., "process_flow", "design_spec").
        content_updated_at: ISO timestamp when content was last updated.
    """
    title: str
    summary: str
    details: str
    content_updated_at: str
    category: Optional[str] = None


@dataclass
class ContentEmbedding:
    """
    Vector embedding stored on the document.

    This field is automatically generated by the Firestore trigger
    and should never be written directly by clients.

    Attributes:
        vector: 768-dimensional embedding vector.
        embedded_at: ISO timestamp when embedding was generated.
        model_version: Model used to generate the embedding.
    """
    vector: List[float]
    embedded_at: str
    model_version: str


@dataclass
class EmbeddableDocument:
    """
    Complete document structure with optional embedding.

    Attributes:
        id: Firestore document ID.
        content: Document content for embedding.
        content_embedding: Auto-generated embedding (read-only).
        created_at: ISO timestamp when document was created.
        updated_at: ISO timestamp when document was last updated.
        created_by: User ID who created the document.

    Example:
        >>> doc = EmbeddableDocument(
        ...     id="doc123",
        ...     content=DocumentContent(
        ...         title="SRAM Cell Design",
        ...         summary="6T SRAM cell for 28nm node",
        ...         details="...",
        ...         content_updated_at="2026-01-15T10:30:00Z"
        ...     )
        ... )
    """
    id: str
    content: DocumentContent
    content_embedding: Optional[ContentEmbedding] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    created_by: Optional[str] = None


# =============================================================================
# Search Types
# =============================================================================

@dataclass
class SearchRequest:
    """
    Request parameters for vector search.

    Attributes:
        query: Natural language search query (minimum 3 characters).
        collection_path: Path to the collection to search (default: "documents").
        limit: Maximum number of results to return (default: 20, max: 50).
        threshold: Cosine distance threshold for filtering (0.0-1.0, default: 0.5).
    """
    query: str
    collection_path: str = "documents"
    limit: int = 20
    threshold: float = 0.5


@dataclass
class SearchResult:
    """
    Individual search result returned by vector search.

    Attributes:
        document_id: Firestore document ID.
        distance: Cosine distance from query embedding (0.0-2.0).
        relevance_score: Human-readable relevance score (0-100).
        summary: Document summary for preview.
        category: Document category.
        title: Document title.
    """
    document_id: str
    distance: float
    relevance_score: int
    summary: str
    category: Optional[str] = None
    title: Optional[str] = None

    def __str__(self) -> str:
        """Format result for display."""
        return f"{self.relevance_score}% - {self.title or self.summary[:50]}"


@dataclass
class SearchResponse:
    """
    Response from vector search function.

    Attributes:
        success: Whether the search completed successfully.
        results: List of matching documents, sorted by relevance.
        query: The original search query.
        total_searched: Number of documents searched (with embeddings).
    """
    success: bool
    results: List[SearchResult]
    query: str
    total_searched: int


# =============================================================================
# Backfill Types
# =============================================================================

@dataclass
class BackfillRequest:
    """
    Request parameters for embedding backfill.

    Attributes:
        collection_path: Path to the collection to process.
        limit: Maximum documents to process (default: 50, max: 200).
    """
    collection_path: str = "documents"
    limit: int = 50


@dataclass
class BackfillResponse:
    """
    Response from backfill function.

    Attributes:
        success: Whether the backfill completed successfully.
        processed: Number of embeddings generated in this call.
        remaining: Estimated remaining documents needing embeddings.
        collection_path: The collection that was processed.
        errors: Document IDs that failed to process.
    """
    success: bool
    processed: int
    remaining: int
    collection_path: str
    errors: List[str] = field(default_factory=list)


@dataclass
class EmbeddingStats:
    """
    Statistics about embedding coverage.

    Attributes:
        total_documents: Total documents in the collection.
        with_embedding: Documents with up-to-date embeddings.
        without_embedding: Documents missing embeddings.
        outdated_embedding: Documents with outdated embeddings.
        coverage_percent: Percentage with current embeddings (0-100).
    """
    total_documents: int
    with_embedding: int
    without_embedding: int
    outdated_embedding: int
    coverage_percent: float


# =============================================================================
# TypedDict versions for raw API responses
# =============================================================================

class SearchResultDict(TypedDict, total=False):
    """Raw search result from Cloud Function."""
    documentId: str
    distance: float
    relevanceScore: int
    summary: str
    category: str
    title: str


class SearchResponseDict(TypedDict):
    """Raw search response from Cloud Function."""
    success: bool
    results: List[SearchResultDict]
    query: str
    totalSearched: int


class BackfillResponseDict(TypedDict):
    """Raw backfill response from Cloud Function."""
    success: bool
    processed: int
    remaining: int
    collectionPath: str
    errors: List[str]


class EmbeddingStatsDict(TypedDict):
    """Raw stats response from Cloud Function."""
    totalDocuments: int
    withEmbedding: int
    withoutEmbedding: int
    outdatedEmbedding: int
    coveragePercent: float


# =============================================================================
# Conversion Helpers
# =============================================================================

def search_result_from_dict(data: SearchResultDict) -> SearchResult:
    """
    Convert raw API response to SearchResult dataclass.

    Args:
        data: Raw dictionary from Cloud Function response.

    Returns:
        SearchResult dataclass instance.
    """
    return SearchResult(
        document_id=data["documentId"],
        distance=data["distance"],
        relevance_score=data["relevanceScore"],
        summary=data.get("summary", ""),
        category=data.get("category"),
        title=data.get("title"),
    )


def search_response_from_dict(data: SearchResponseDict) -> SearchResponse:
    """
    Convert raw API response to SearchResponse dataclass.

    Args:
        data: Raw dictionary from Cloud Function response.

    Returns:
        SearchResponse dataclass instance.
    """
    return SearchResponse(
        success=data["success"],
        results=[search_result_from_dict(r) for r in data["results"]],
        query=data["query"],
        total_searched=data["totalSearched"],
    )


def backfill_response_from_dict(data: BackfillResponseDict) -> BackfillResponse:
    """
    Convert raw API response to BackfillResponse dataclass.

    Args:
        data: Raw dictionary from Cloud Function response.

    Returns:
        BackfillResponse dataclass instance.
    """
    return BackfillResponse(
        success=data["success"],
        processed=data["processed"],
        remaining=data["remaining"],
        collection_path=data["collectionPath"],
        errors=data.get("errors", []),
    )


def embedding_stats_from_dict(data: EmbeddingStatsDict) -> EmbeddingStats:
    """
    Convert raw API response to EmbeddingStats dataclass.

    Args:
        data: Raw dictionary from Cloud Function response.

    Returns:
        EmbeddingStats dataclass instance.
    """
    return EmbeddingStats(
        total_documents=data["totalDocuments"],
        with_embedding=data["withEmbedding"],
        without_embedding=data["withoutEmbedding"],
        outdated_embedding=data["outdatedEmbedding"],
        coverage_percent=data["coveragePercent"],
    )
